### ISSUE TITLE
install documentation missing

### ISSUE THREAD

**Issue by ginolhac** [MikkelSchubert/retable#1]
thanks for the release! I am used to the python version that was already pretty useful.
For this `rust` version, I think some install notes would be nice. Especially because it is rather easy, at least on Mac OS, with [homebrew](http://brew.sh) installed.

```
brew install rust
cargo build
```

**Comment by MikkelSchubert** [comment]
Thanks for the suggestion; I've updated the documentation with some basic instructions, though I decided to leave out brew since it is not required (and Rust has a official OSX pkg).
